### ISSUE TITLE
Daemon detecting servers as crashed without a reason

### ISSUE THREAD

**Issue by karatemaccie** [PufferPanel/Scales#88]
Exactly what the title says. The daemon detects servers as crashed when there is enough RAM avaible (double the amount that should be used) and without any plugins. Even on a completely clean server.

**Comment by CryLegend** [comment]
Same issue here. Due to [a lack of stats](https://github.com/PufferPanel/Scales/blob/master/lib/process.js#L674). Contact me if you need any further information.

**Comment by LordRalex** [comment]
"Contact me if you need any further information."

As a dev, this means nothing to me. All your comment is doing is a "+1", which is not that valuable to me. 

If you are going to offer information, simply give the information. It's meaningless for me to have to go out of my way to ask for it, and is actually aggravating to see. It benefits no one.

**Comment by CryLegend** [comment]
I mean if you need access to my server to have a look ;)

**Comment by schrej** [comment]
As we are having the same issues i did some research. I do not think it has anything to do with the crash detection mentioned by @CryLegend.
The [log output](https://github.com/PufferPanel/Scales/blob/master/lib/process.js#L383) suggests that the PTY "exits", at least in our case. This happens when the server is having a massive lag spike making it unresponsive for a few seconds. I **think** that this could be caused by the [pty.js](https://github.com/chjj/pty.js) module. I'm not that good with C++ and am not sure how libuv (which is the async library used by them) works, but my guess is that pty.js marks the pty as exited when its not responding anymore.
The exit event causes the docker container to be shut down which will kill the server obviously.

I'll look into this further when i have more time, maybe someone here has an idea. We currently are inspecting the two params of the callback and are trying to get crashes without reason to look at the params (which are the exitcode and the signal from the PTY).

**Comment by LordRalex** [comment]
Because of how Docker and the JVM works, I think what is actually happening is that Docker is killing the server.

Since we specify the memory limit on the container, and _then_ use that same limit on just the Java heap, in theory, what may be happening is that the JVM uses the memory it thinks it can use, but Docker/JVM pukes when it realizes it can't.

Has anyone confirmed this is _only_ happening when Docker is being used? I have not determined based on logs if this also has happened without docker being involved.

**Comment by schrej** [comment]
It seems like you are right about docker killing the container.
We just tested it with a server that would crash all the time running with PufferPanel.
We set the container to 15G of ram and allowed java to use only 14gb. It's now running since 14hrs without any crashes. Maybe the "use the maximum ram for the server" option should leave some ram (how much needs to be researched) for the jvm to use.

This could help maybe ([source](https://docs.docker.com/engine/reference/run/#/user-memory-constraints))

> By default, kernel kills processes in a container if an out-of-memory (OOM) error occurs. To change this behaviour, use the --oom-kill-disable option. Only disable the OOM killer on containers where you have also set the -m/--memory option. If the -m flag is not set, this can result in the host running out of memory and require killing the host’s system processes to free memory.

**Comment by LordRalex** [comment]
I'm not a fan of the arbitrary memory setting, since it's not something we can easily code against without affecting the server in some way. Determining a "value" to use for that is not something that'd I want to make, considering Scales is only getting security/critical updates.

Since this one has a work-around (disabling Docker), then that's the approach I think we will just need to recommend. The Docker implementation has been nothing _but_ trouble ever since it was hackily implemented, and it's still causing problems. 

While I like the idea of Docker for security, this project has shown just how troublesome it can be to use. I know that their API should be simplier than this, and our implementation of using it was terrible, but it's too much work to try to fix it at this stage.

For anyone else getting this problem, the only recommendation I want to make is to just disable Docker. That's the best fix IMO for the problem.
Otherwise, you can edit the following line and add in the flag above:
https://github.com/PufferPanel/Scales/blob/master/lib/controller/system.js#L200
